
package ventanas;

import com.itextpdf.text.BadElementException;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import static com.itextpdf.text.Element.ALIGN_LEFT;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import dao.ClienteDAO;
import dao.ProductoDAO;
import dao.ventasDAO;
import java.awt.Desktop;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import modelo.Cliente;
import modelo.Conexion;
import modelo.DetalleVenta;
import modelo.Producto;
import modelo.ventas;


/**
 *
 * @author famil
 */
public class VentasForm extends javax.swing.JInternalFrame {

    ProductoDAO pdao = new ProductoDAO();
    Producto producto = new Producto();
    ClienteDAO cli = new ClienteDAO();
    Cliente c = new Cliente();
    int cont = 0;
    ventas v = new ventas();
    DetalleVenta dv= new DetalleVenta();
    ventasDAO vdao = new ventasDAO();
    Conexion cc = new Conexion();
    Connection cn = cc.ConectarBasedeDatos();
    

    DefaultTableModel modelo = new DefaultTableModel();
    DefaultTableModel tabla = new DefaultTableModel();
    int idp;
    int cant;
    float pre;
    double tpagar;

    public VentasForm() {
        initComponents();
    
        txtFecha.setText(fechaActual());
        txtCodigoCliente.requestFocus();
        
        Statement sen1;
        int cont=1;
        try {
            sen1 = cn.createStatement();
                  ResultSet rs2 = sen1.executeQuery("select MAX(idVentas) from ventas");
              while(rs2.next()){
                   int resul = Integer.parseInt(rs2.getString(1)) ; 
                   resul= resul + cont;
                   txtFactura.setText(String.valueOf(resul) );
                   
     } 
             
        } catch (SQLException ex) {
            Logger.getLogger(ClienteForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        jBagregar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        cCliente = new javax.swing.JLabel();
        txtCodigoCliente = new javax.swing.JTextField();
        txtTipoCliente = new javax.swing.JTextField();
        BtnBuscar = new javax.swing.JButton();
        txtStock = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jBguardar = new javax.swing.JButton();
        txtTotalPagar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTventas = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtFactura = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setClosable(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel2.setText("DESCRIPCION");
        jLabel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setText("CANTIDAD");
        jLabel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setText("PRECIO");
        jLabel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodigoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoKeyTyped(evt);
            }
        });

        txtDescripcion.setEditable(false);

        txtPrecio.setEditable(false);

        jBagregar.setText("AGREGAR");
        jBagregar.setBorder(new javax.swing.border.MatteBorder(null));
        jBagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBagregarActionPerformed(evt);
            }
        });
        jBagregar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBagregarKeyPressed(evt);
            }
        });

        jLabel5.setText("CODIGO");
        jLabel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        cCliente.setText("COD.CLIENTE");
        cCliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtCodigoCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodigoClienteKeyPressed(evt);
            }
        });

        txtTipoCliente.setEditable(false);

        BtnBuscar.setText("BUSCAR CLIENTE");
        BtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarActionPerformed(evt);
            }
        });

        txtStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStockActionPerformed(evt);
            }
        });

        jLabel12.setText("STOCK");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cCliente)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnBuscar)
                        .addGap(50, 50, 50))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 389, Short.MAX_VALUE)
                        .addComponent(jBagregar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtCodigoCliente, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCodigo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
                                .addGap(81, 81, 81)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtTipoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cCliente)
                    .addComponent(txtCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTipoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBagregar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(35, 35, 35))
        );

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));

        jBguardar.setText("GUARDAR VENTA");
        jBguardar.setBorder(new javax.swing.border.MatteBorder(null));
        jBguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBguardarActionPerformed(evt);
            }
        });

        txtTotalPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalPagarActionPerformed(evt);
            }
        });

        jLabel1.setText("TOTAL A PAGAR");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jBguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(txtTotalPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(32, 32, 32))
        );

        jTventas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTventas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ITEM", "CODIGO", "DESCRIPCION", "CANTIDAD", "PRECIO X UNIDAD", "TOTAL"
            }
        ));
        jTventas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(jTventas);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logotodomoda.png"))); // NOI18N

        txtFactura.setEditable(false);

        txtFecha.setEditable(false);

        jLabel7.setFont(new java.awt.Font("Bodoni MT", 2, 12)); // NOI18N
        jLabel7.setText("FACTURA:");

        jLabel8.setFont(new java.awt.Font("Bodoni MT", 2, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 204));
        jLabel8.setText("CUIT: 33-71076085-9");

        jLabel9.setFont(new java.awt.Font("Bodoni MT", 2, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 204));
        jLabel9.setText("TELEFONO: 11-2390-1047");

        jLabel10.setFont(new java.awt.Font("Bodoni MT", 2, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 204));
        jLabel10.setText("DIRECION: AV. CAZON 1577 - TIGRE");

        jLabel11.setFont(new java.awt.Font("Bodoni MT", 2, 12)); // NOI18N
        jLabel11.setText("FECHA DE EMISION:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(jLabel10))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(307, 307, 307)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(txtFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(216, 216, 216)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(51, 51, 51))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 774, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  
    
    public static String fechaActual(){
    Date fecha = new Date();
    SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/YYYY");
    return formatoFecha.format(fecha);
    
            
}
    private void txtCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyTyped

    }//GEN-LAST:event_txtCodigoKeyTyped

    private void txtCodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!"".equals(txtCodigo.getText())) {
                int id = Integer.parseInt(txtCodigo.getText());
                Producto p = pdao.listarID(id);
                if (p.getidProducto() != 0) {
                    txtDescripcion.setText("" + p.getDescripcion());
                    txtPrecio.setText("" + p.getPrecio_venta());
                    txtStock.setText("" + p.getCantidad());
                    txtCantidad.requestFocus();

                } else {
                    txtDescripcion.setText("");
                    txtPrecio.setText("");
                    txtCodigo.requestFocus();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Ingrese un codigo de producto");
                txtCodigo.requestFocus();
            }

        }

    }//GEN-LAST:event_txtCodigoKeyPressed

    private void jBagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBagregarActionPerformed
        // TODO add your handling code here:

        agregarProducto();
        limpiarCampos();
        double total;


    }//GEN-LAST:event_jBagregarActionPerformed

    private void txtCodigoClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoClienteKeyPressed
        int confirmado;
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!"".equals(txtCodigoCliente.getText())) {
                int id = Integer.parseInt(txtCodigoCliente.getText());
                Cliente c = cli.listarID(id);
                if (c.getIdCliente() != 0) {
                    txtTipoCliente.setText("" + c.getNombre());
                    txtCodigo.requestFocus();

                } else {
                    JOptionPane.showMessageDialog(null, "El cliente no existe");
                    confirmado = JOptionPane.showConfirmDialog(null, "¿Desea agregar al cliente?");

                    if (JOptionPane.OK_OPTION == confirmado) {
                        ClienteForm cli = new ClienteForm();

                        cli.setVisible(true);
                    }

                }

            } else {
                JOptionPane.showMessageDialog(null, "Ingrese un codigo de cliente");
                txtCodigo.requestFocus();
            }
        }

    }//GEN-LAST:event_txtCodigoClienteKeyPressed

    private void jBagregarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBagregarKeyPressed

    }//GEN-LAST:event_jBagregarKeyPressed

    private void BtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarActionPerformed
        // TODO add your handling code here:
        TablaCliente tabla = new TablaCliente();
        tabla.setVisible(true);
    }//GEN-LAST:event_BtnBuscarActionPerformed

    private void jBguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBguardarActionPerformed
      
        
      
       int confirmado =JOptionPane.showConfirmDialog(null, "¿Desea imprimir la venta?");
            
            if(JOptionPane.OK_OPTION == confirmado){
             try {
              pdf();
          } catch (DocumentException ex) {
              Logger.getLogger(VentasForm.class.getName()).log(Level.SEVERE, null, ex);
          } catch (IOException ex) {
              Logger.getLogger(VentasForm.class.getName()).log(Level.SEVERE, null, ex);
          }
            }
            registrarVenta();  
        
            registrarDetalle();
            limpiarCliente();
            actualizarStock();
            limpiarTabla();
            
    }//GEN-LAST:event_jBguardarActionPerformed
    private void registrarVenta() {
        
        int idCliente = Integer.parseInt(txtCodigoCliente.getText());
        int idvendedor=1;
        double total = Double.parseDouble(txtTotalPagar.getText());
        
        v.setIdCliente(idCliente);
        v.setIdVendedor(idvendedor);
        v.setTotal((float) total);
        vdao.RegistrarVenta(v);
        
    }
    private void registrarDetalle() {
        int idVentas= Integer.parseInt(txtFactura.getText());
        
                for(int i=0; i<jTventas.getRowCount(); i++){
                   int idp= Integer.parseInt(jTventas.getValueAt(i, 1).toString());
                   int cant=Integer.parseInt(jTventas.getValueAt(i, 3).toString());
                   float pre= Float.parseFloat(jTventas.getValueAt(i, 4).toString());
                   dv.setIdVentas(idVentas);
                   dv.setIdProducto(idp);
                   dv.setCantidad(cant);
                   dv.setPrecio(pre);
           
                   vdao.RegistrarDetalleVentas(dv);
            
                }
        
    }
    private void txtTotalPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalPagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalPagarActionPerformed

    private void txtStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStockActionPerformed
        // TODO add your handling code here:
        int stock= Integer.parseInt(txtStock.getText());
        if(stock < 3){
            JOptionPane.showMessageDialog(null, "Quedan pocas unidades del producto");
            
        }
    }//GEN-LAST:event_txtStockActionPerformed
    public void agregarProducto() {
        double total;

        modelo = (DefaultTableModel) jTventas.getModel();

        idp = Integer.parseInt(txtCodigo.getText());
        String nombre = txtDescripcion.getText();
        pre = Float.parseFloat(txtPrecio.getText());
        cant = Integer.parseInt(txtCantidad.getText());
        total = cant * pre;
        ArrayList lista = new ArrayList();
        cont = cont + 1;

        if (cant > 0) {

            lista.add(cont);
            lista.add(idp);
            lista.add(nombre);
            lista.add(cant);
            lista.add(pre);
            lista.add(total);
            Object[] obj = new Object[6];
            obj[0] = lista.get(0);
            obj[1] = lista.get(1);
            obj[2] = lista.get(2);
            obj[3] = lista.get(3);
            obj[4] = lista.get(4);
            obj[5] = lista.get(5);
            modelo.addRow(obj);
            jTventas.setModel(modelo);
            calcularTotal();

        } else {
            JOptionPane.showMessageDialog(this, "ingrese la cantidad");
        }
    }

    void calcularTotal() {
        tpagar = 0;
        for (int i = 0; i < jTventas.getRowCount(); i++) {
            cant = Integer.parseInt(jTventas.getValueAt(i, 3).toString());
            pre = Float.parseFloat(jTventas.getValueAt(i, 4).toString());
            tpagar = tpagar + (cant * pre);
        }
        txtTotalPagar.setText("" + tpagar);

    }
    private void pdf() throws DocumentException, BadElementException, IOException{
         
        try {
            int id= Integer.parseInt(txtFactura.getText());
            Document documento = new Document();
            FileOutputStream archivo;
            File file = new File ("src/pdf/ventas"+ id +".pdf");
            archivo = new FileOutputStream (file);
            PdfWriter.getInstance(documento,archivo ).setInitialLeading(20);
           
            documento.open();

           Image img = Image.getInstance("src/imagenes/logotodomoda.png");
           Paragraph fecha = new Paragraph ();
           Font letra = new Font(Font.FontFamily.COURIER,10, Font.BOLD, BaseColor.DARK_GRAY);
           fecha.add(Chunk.NEWLINE);
           Date date = new Date ();
           fecha.add("Factura: "+ id +"\n" + "Fecha : " + new SimpleDateFormat("dd-MM-yyyy").format(date)+ "\n\n");
           fecha.setAlignment(fecha.ALIGN_RIGHT);
           fecha.setFont(letra);
          
           documento.add(img);
          
           documento.add(fecha);
           
           PdfPTable tabla = new PdfPTable(5);
           tabla.setHorizontalAlignment(Element.ALIGN_CENTER);
           documento.add(new Paragraph("CUIT: 33-72076085-9",FontFactory.getFont("arial", 8, Font.ITALIC,BaseColor.DARK_GRAY)));
           documento.add(new Paragraph("Razon: Todo Moda" ,FontFactory.getFont("arial", 8, Font.ITALIC,BaseColor.DARK_GRAY)));
           documento.add(new Paragraph("Telefono: 11-2390-1047" ,FontFactory.getFont("arial", 8, Font.ITALIC,BaseColor.DARK_GRAY)));
           documento.add(new Paragraph("Direccion: Av. Cazon 1577" ,FontFactory.getFont("arial", 8, Font.ITALIC,BaseColor.DARK_GRAY)));
           documento.add(new Paragraph("Localidad: Tigre " ,FontFactory.getFont("arial", 8, Font.ITALIC,BaseColor.DARK_GRAY)));
           
           
           tabla.addCell("");
         
           tabla.addCell(fecha);
           
          

             documento.add(tabla);
             
             Paragraph detalle = new Paragraph();
             detalle.add(Chunk.NEWLINE);
             detalle.add("DETALLE DE VENTA"+"\n\n");
             documento.add(detalle);
             
             PdfPTable tablacli = new PdfPTable(2);
             tablacli.setWidthPercentage(100);
             tablacli.getDefaultCell().setBorder(0);
             float [] columnacli = new float[]{20f,50f};
             tablacli.setWidths(columnacli);
             tablacli.setHorizontalAlignment(ALIGN_LEFT);
             PdfPCell cli1 = new PdfPCell (new Phrase("Codigo de Cliente: "));
             PdfPCell cli2 = new PdfPCell (new Phrase("Nombre: "+"\n"));
             cli1.setBorder(0);
             cli2.setBorder(0);
             tablacli.addCell(cli1);
             tablacli.addCell(cli2);
             tablacli.addCell(txtCodigoCliente.getText());
             tablacli.addCell(txtTipoCliente.getText());
             
             documento.add(tablacli);
             
             //agregar productos
             PdfPTable tablapro = new PdfPTable (4);
             tablapro.setWidthPercentage(100);
             tablapro.getDefaultCell().setBorder(0);
             float [] columnapro = new float[]{20f, 60f,20f, 20f};
             tablapro.setWidths(columnapro);
             tablapro.setHorizontalAlignment(ALIGN_LEFT);
             PdfPCell pro1 = new PdfPCell (new Phrase("\n\n"+ "CANTIDAD: "));
             PdfPCell pro2 = new PdfPCell (new Phrase("\n\n"+"DESCRIPCION: "));
             PdfPCell pro3= new PdfPCell (new Phrase("\n\n"+"PRECIO UNITARIO: "));
             PdfPCell pro4= new PdfPCell (new Phrase("\n\n"+"TOTAL: $"));
             pro1.setBorder(0);
             pro2.setBorder(0);
             pro3.setBorder(0);
             pro4.setBorder(0);
             tablapro.addCell(pro1);
             tablapro.addCell(pro2);
             tablapro.addCell(pro3);
             tablapro.addCell(pro4);
             for (int i = 0; i < jTventas.getRowCount(); i++) {
                 String cantidad = jTventas.getValueAt(i,3).toString();
                 String descripcion = jTventas.getValueAt(i,2).toString();
                 String precio= jTventas.getValueAt(i,4).toString();
                 String total= jTventas.getValueAt(i, 5).toString();
                 
                 tablapro.addCell(cantidad);
                 tablapro.addCell(descripcion);
                 tablapro.addCell(precio);
                 tablapro.addCell(total);
                 
                
            }
             documento.add(tablapro);
             Paragraph info = new Paragraph();
             info.add(Chunk.NEWLINE);
             info.add("Total a pagar: " + txtTotalPagar.getText());
             info.setAlignment(Element.ALIGN_RIGHT);
             documento.add(info);
             
           
           documento.close();
           Desktop.getDesktop().open(file);
        } catch(FileNotFoundException ex){
            
        }
    
           
        }
        public void limpiarCampos (){
    
        txtCodigo.setText("");
        txtDescripcion.setText("");
        txtPrecio.setText("");
        txtCantidad.setText("");
        txtStock.setText("");
        
        txtCodigo.requestFocus();
        
        }
        public void limpiarCliente(){
          txtCodigoCliente.setText("");
          txtTipoCliente.setText("");
           txtTotalPagar.setText("");
          txtCodigoCliente.requestFocus();
        }
        public void limpiarTabla(){
          tabla= (DefaultTableModel) jTventas.getModel();
          int fila= jTventas.getRowCount();
          for(int x=0; x<fila; x++){
              tabla.removeRow(0);
          }
         
        }
        private void actualizarStock(){
         
            for(int x=0; x<modelo.getRowCount(); x++){
              Producto pr= new Producto();
              idp= Integer.parseInt( jTventas.getValueAt(x, 1).toString());
              cant=Integer.parseInt(jTventas.getValueAt(x, 3).toString());
              pr= pdao.listarID(idp);
              int stock= pr.getCantidad()-cant;
              pdao.ActualizarStock(stock, idp);
              
                // int cod= Integer.parseInt(jTventas.getValueAt(x, 1).toString());
                //int cantid= Integer.parseInt(jTventas.getValueAt(x, 3).toString());
                
              //  producto = pdao.BuscarPro(cod);
              //  int StockActual= producto.getCantidad()- cantid;
              //  pdao.ActualizarStock(StockActual, cod);
            }
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBuscar;
    private javax.swing.JLabel cCliente;
    public static javax.swing.JButton jBagregar;
    private javax.swing.JButton jBguardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTventas;
    private javax.swing.JTextField txtCantidad;
    public static javax.swing.JTextField txtCodigo;
    public static javax.swing.JTextField txtCodigoCliente;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtFactura;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtStock;
    public static javax.swing.JTextField txtTipoCliente;
    private javax.swing.JTextField txtTotalPagar;
    // End of variables declaration//GEN-END:variables
}
