/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import com.mysql.cj.jdbc.result.ResultSetMetaData;
import dao.ClienteDAO;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Cliente;
import modelo.Conexion;

/**
 *
 * @author Gisel Muñoz
 */
public class ListaDeClientes extends javax.swing.JInternalFrame {

    ClienteDAO clienteDAO= new ClienteDAO();
    ResultSet resultado;
    DefaultTableModel modelo = new DefaultTableModel();
    
    public ListaDeClientes() {
        initComponents();
        
         try {
                
                JtClientes.setModel(modelo);

                resultado = clienteDAO.list();

                ResultSetMetaData resultadosMd = (ResultSetMetaData) resultado.getMetaData();
                int cantidadDeColumnas = resultadosMd.getColumnCount();

              
                modelo.addColumn("Codigo");
                modelo.addColumn("Nombre");
                modelo.addColumn("Apellido");
                modelo.addColumn("Cuit");
                JtClientes.setModel(modelo);

                while (resultado.next()) {

                    Object[] filas = new Object[cantidadDeColumnas];

                    for (int x = 0; x < cantidadDeColumnas; x++) {
                        filas[x] = resultado.getObject(x + 1);
                    }
                    modelo.addRow(filas);
                }

            } catch (SQLException ex) {
                System.out.print("No funciona");

            }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JtClientes = new javax.swing.JTable();
        jbAgregar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        jbBorrar = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("CLIENTES");

        jLabel1.setFont(new java.awt.Font("Century", 2, 11)); // NOI18N
        jLabel1.setText("CLIENTES");

        JtClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        JtClientes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JtClientesKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(JtClientes);

        jbAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agregar-usuario (1)_opt.png"))); // NOI18N
        jbAgregar.setText("AGREGAR");
        jbAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAgregarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lupa_opt.png"))); // NOI18N
        jLabel2.setText("BUSCADOR");

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        jbBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar_opt.png"))); // NOI18N
        jbBorrar.setText("BORRAR");
        jbBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jbBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE))
                .addGap(81, 81, 81))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAgregar)
                    .addComponent(jLabel2))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbBorrar)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyPressed
        // TODO add your handling code here:
        String[] nombres = {"Codigo", "Nombre", "Apellido", "Cuit"};
        String[] registro = new String[30];
        String valor = txtBuscar.getText();

        DefaultTableModel model = new DefaultTableModel(null, nombres);

        try {
            resultado = clienteDAO.search(valor);

            while (resultado.next()) {
                registro[0] = resultado.getString("idCliente");
                registro[1] = resultado.getString("nombre");
                registro[2] = resultado.getString("apellido");
                registro[3] = resultado.getString("cuit");
                model.addRow(registro);
            }
            JtClientes.setModel(model);

        } catch (SQLException ex) {
            Logger.getLogger(ListaDeProveedores.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtBuscarKeyPressed

    private void jbAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAgregarActionPerformed
        // TODO add your handling code here:
        ClienteForm clientes = new ClienteForm();
        clientes.setVisible(true);
    }//GEN-LAST:event_jbAgregarActionPerformed

    private void jbBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBorrarActionPerformed
        // TODO add your handling code here:
                int fila = JtClientes.getSelectedRow();

        String valor = JtClientes.getValueAt(fila, 0).toString();

        try {
            Conexion cc = new Conexion();
           
            Connection cn = cc.ConectarBasedeDatos();
            String sql = "UPDATE cliente SET  activo  = '0' WHERE idCliente = '" + valor + "' ";
            PreparedStatement eliminar = cn.prepareStatement(sql);
            eliminar.executeUpdate();
            JOptionPane.showConfirmDialog(null, "¿Desea borrar el cliente?");
            JOptionPane.showMessageDialog(null, "El cliente ha sido borrado con exito");

        } catch (SQLException e) {
     
        }
        
    }//GEN-LAST:event_jbBorrarActionPerformed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_txtBuscarKeyReleased

    private void JtClientesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JtClientesKeyReleased
        // TODO add your handling code here:
            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            Cliente cli = new Cliente();
            int codigo =Integer.parseInt( JtClientes.getValueAt(JtClientes.getSelectedRow(),0).toString());
            String nombre = JtClientes.getValueAt(JtClientes.getSelectedRow(), 1).toString();
            String apellido = JtClientes.getValueAt(JtClientes.getSelectedRow(), 2).toString();
            String cuit = JtClientes.getValueAt(JtClientes.getSelectedRow(), 3).toString();
           
            cli.setIdCliente(codigo);
            cli.setNombre(nombre);
            cli.setApellido(apellido);
            cli.setCuit(cuit);
            clienteDAO.update(cli);
        
            JOptionPane.showMessageDialog(null, "El cliente  fue modificado con éxito");

        }
    }//GEN-LAST:event_JtClientesKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JtClientes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAgregar;
    private javax.swing.JButton jbBorrar;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
